globs:
  - "**/*.md"
ignores:
  - ".git"
  - "node_modules"
  - ".agent/skills"
  - ".agents/skills"
config:
  MD004: false
  MD012: false
  MD013: false
  MD025: false
  MD026: false
  MD032: false
  MD033: false
