//! `tzlint_ast` — the permanently-frozen `AstCoreV1` ABI for `TsuzuLint`.
//!
//! This crate defines the on-the-wire AST that every rule (native or plugin) reads. It is
//! **index-based**: an [`Ast`] owns a contiguous `Vec<`[`Node`]`>` and the full source
//! [`text`](Ast::text) once; each [`Node`] refers to other nodes by [`NodeId`] (a `u32`
//! index) and to its source text by an **absolute** byte [`Span`] into `Ast::text`. There
//! are no lifetimes, no pointers, and no per-node allocations, so the whole tree
//! [archives cleanly with rkyv](https://rkyv.org) and is read **in place** (zero-copy) by
//! consumers — no deserialize step.
//!
//! # Frozen layout (`AstCoreV1`)
//!
//! The archived byte layout is a **frozen ABI**. It is pinned **little-endian** with
//! **32-bit relative pointers** (see the workspace `rkyv` features) so one archive is
//! byte-identical across hosts and readable on both native (64-bit) and `wasm32`
//! (32-bit). The `golden_archived_layout_is_frozen` test captures the exact wire image of
//! a canonical tree; any drift — including drift from an rkyv upgrade — fails CI. Changing
//! the layout is a deliberate, major-version act.
//!
//! The frozen field set of [`Node`] is `{ kind, span, parent, first_child, next_sibling }`.
//! Additional per-node data (morphology, readings, …) lives in *separate* additive
//! archived tables keyed by [`NodeId`], never by extending [`Node`]; see `abi-spec.md`.
//!
//! # `no_std`
//!
//! The crate is `#![no_std]` (alloc only) for normal and `wasm32` builds, so it can sit on
//! the guest side of the plugin ABI. Tests run under `std`.

#![cfg_attr(not(test), no_std)]
// The only `unsafe` in this crate is generated by the rkyv derive macros (`unsafe impl
// Portable`/`CheckBytes` for the archived types), which is sound per rkyv's contract.
// This crate contains **no hand-written `unsafe`** — boundary reads use the checked
// `rkyv::access` (see `abi-spec.md`), and that invariant is enforced by review.
#![allow(unsafe_code)]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;

use rkyv::{Archive, Serialize};

/// An absolute, half-open byte range `[start, end)` into [`Ast::text`].
///
/// Offsets are **bytes**, not chars or columns — a node's text is exactly
/// `&ast.text[span.start..span.end]`. Conversion to user-facing `(line, column)` happens
/// once, at output, via the position mapper (in `tzlint_core`).
#[derive(Archive, Serialize, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Span {
    pub start: u32,
    pub end: u32,
}

impl Span {
    /// A span covering `[start, end)`.
    #[inline]
    #[must_use]
    pub const fn new(start: u32, end: u32) -> Self {
        Self { start, end }
    }

    /// Length in bytes (saturating; an inverted span reports `0`).
    #[inline]
    #[must_use]
    pub const fn len(self) -> u32 {
        self.end.saturating_sub(self.start)
    }

    /// Whether the span covers zero bytes.
    #[inline]
    #[must_use]
    pub const fn is_empty(self) -> bool {
        self.end <= self.start
    }
}

/// Index of a node into [`Ast::nodes`].
#[derive(Archive, Serialize, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NodeId(pub u32);

/// An optional [`NodeId`], encoded as a bare `u32` with [`u32::MAX`] as the `None`
/// sentinel.
///
/// This is deliberately **not** `Option<NodeId>`: rkyv would archive that with an extra
/// discriminant byte and non-niche layout. Storing the sentinel keeps every link a plain
/// little-endian `u32`, so the frozen layout is trivial and golden-byte-stable.
#[derive(Archive, Serialize, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct OptionNodeId(pub u32);

impl OptionNodeId {
    /// The `None` sentinel (`u32::MAX`).
    pub const NONE: Self = Self(u32::MAX);

    /// Wrap a present [`NodeId`]. (A real tree never has `u32::MAX` nodes, so the index
    /// can never collide with the sentinel.)
    #[inline]
    #[must_use]
    pub const fn some(id: NodeId) -> Self {
        Self(id.0)
    }

    /// Decode to an [`Option<NodeId>`].
    #[inline]
    #[must_use]
    pub const fn get(self) -> Option<NodeId> {
        if self.0 == u32::MAX {
            None
        } else {
            Some(NodeId(self.0))
        }
    }

    /// Whether this is the `None` sentinel.
    #[inline]
    #[must_use]
    pub const fn is_none(self) -> bool {
        self.0 == u32::MAX
    }
}

/// The kind of a [`Node`].
///
/// This is a forward-compatible **open enum**: the wire value is a bare `u32`, so *any*
/// value round-trips and an unknown kind produced by a newer writer is **preserved and
/// treated as opaque** by an older reader rather than rejected (checked `rkyv::access`
/// validates a plain `u32`, never a closed variant set). The known kinds map 1:1 onto the
/// markdown-rs `mdast::Node` vocabulary; the `mdast → index-AST` transform in
/// `tzlint_core` is total over that vocabulary.
///
/// Discriminants are **frozen**: a new kind appends the next free value; existing values
/// never move or get reused.
#[derive(Archive, Serialize, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NodeKind(u32);

impl NodeKind {
    // ── Root ────────────────────────────────────────────────────────────────────────
    /// `mdast::Root` — the document root.
    pub const ROOT: Self = Self(0);

    // ── Block / flow content ─────────────────────────────────────────────────────────
    /// `mdast::Paragraph`.
    pub const PARAGRAPH: Self = Self(1);
    /// `mdast::Heading`.
    pub const HEADING: Self = Self(2);
    /// `mdast::ThematicBreak` (`---`).
    pub const THEMATIC_BREAK: Self = Self(3);
    /// `mdast::Blockquote`.
    pub const BLOCKQUOTE: Self = Self(4);
    /// `mdast::List`.
    pub const LIST: Self = Self(5);
    /// `mdast::ListItem`.
    pub const LIST_ITEM: Self = Self(6);
    /// `mdast::Code` — a fenced or indented code block.
    pub const CODE: Self = Self(7);
    /// `mdast::Html` — raw HTML (flow or phrasing; mdast uses one node type for both).
    pub const HTML: Self = Self(8);
    /// `mdast::Definition` — a link reference definition.
    pub const DEFINITION: Self = Self(9);
    /// `mdast::FootnoteDefinition` (GFM).
    pub const FOOTNOTE_DEFINITION: Self = Self(10);
    /// `mdast::Table` (GFM).
    pub const TABLE: Self = Self(11);
    /// `mdast::TableRow` (GFM).
    pub const TABLE_ROW: Self = Self(12);
    /// `mdast::TableCell` (GFM).
    pub const TABLE_CELL: Self = Self(13);
    /// `mdast::Yaml` — YAML frontmatter.
    pub const YAML: Self = Self(14);
    /// `mdast::Toml` — TOML frontmatter.
    pub const TOML: Self = Self(15);
    /// `mdast::Math` — a block math expression.
    pub const MATH: Self = Self(16);

    // ── Inline / phrasing content ────────────────────────────────────────────────────
    /// `mdast::Text` — literal text (the primary prose carrier).
    pub const TEXT: Self = Self(17);
    /// `mdast::Emphasis` (`*…*`).
    pub const EMPHASIS: Self = Self(18);
    /// `mdast::Strong` (`**…**`).
    pub const STRONG: Self = Self(19);
    /// `mdast::Delete` — strikethrough (GFM).
    pub const DELETE: Self = Self(20);
    /// `mdast::InlineCode`.
    pub const INLINE_CODE: Self = Self(21);
    /// `mdast::InlineMath`.
    pub const INLINE_MATH: Self = Self(22);
    /// `mdast::Break` — a hard line break.
    pub const BREAK: Self = Self(23);
    /// `mdast::Link`.
    pub const LINK: Self = Self(24);
    /// `mdast::LinkReference`.
    pub const LINK_REFERENCE: Self = Self(25);
    /// `mdast::Image`.
    pub const IMAGE: Self = Self(26);
    /// `mdast::ImageReference`.
    pub const IMAGE_REFERENCE: Self = Self(27);
    /// `mdast::FootnoteReference` (GFM).
    pub const FOOTNOTE_REFERENCE: Self = Self(28);

    // ── MDX ──────────────────────────────────────────────────────────────────────────
    // Only produced when MDX parsing is enabled. Defined here so the transform is lossless
    // over the *entire* mdast vocabulary even if MDX is turned on later.
    /// `mdast::MdxFlowExpression`.
    pub const MDX_FLOW_EXPRESSION: Self = Self(29);
    /// `mdast::MdxTextExpression`.
    pub const MDX_TEXT_EXPRESSION: Self = Self(30);
    /// `mdast::MdxJsxFlowElement`.
    pub const MDX_JSX_FLOW_ELEMENT: Self = Self(31);
    /// `mdast::MdxJsxTextElement`.
    pub const MDX_JSX_TEXT_ELEMENT: Self = Self(32);
    /// `mdast::MdxjsEsm`.
    pub const MDXJS_ESM: Self = Self(33);

    /// Number of known kinds. Discriminants `< COUNT` are known; anything `>= COUNT` is an
    /// unknown/opaque kind from a newer producer.
    pub const COUNT: u32 = 34;

    /// The raw wire discriminant.
    #[inline]
    #[must_use]
    pub const fn as_u32(self) -> u32 {
        self.0
    }

    /// Wrap a raw wire discriminant. Total: unknown values are preserved (see the type docs
    /// on forward compatibility).
    #[inline]
    #[must_use]
    pub const fn from_u32(value: u32) -> Self {
        Self(value)
    }

    /// Whether this is one of the known [`NodeKind`] constants.
    #[inline]
    #[must_use]
    pub const fn is_known(self) -> bool {
        self.0 < Self::COUNT
    }
}

/// One AST node — the frozen `AstCoreV1` record.
///
/// Children are a singly-linked list: [`first_child`](Node::first_child) then
/// [`next_sibling`](Node::next_sibling) chains. [`parent`](Node::parent) is always a valid
/// [`NodeId`]; by convention the root's parent is the root itself.
#[derive(Archive, Serialize, Debug, Clone, PartialEq, Eq)]
pub struct Node {
    /// The node's kind.
    pub kind: NodeKind,
    /// Absolute byte range of the node's source text in [`Ast::text`].
    pub span: Span,
    /// The parent node (the root's parent is the root itself).
    pub parent: NodeId,
    /// First child, or [`OptionNodeId::NONE`] for a leaf.
    pub first_child: OptionNodeId,
    /// Next sibling, or [`OptionNodeId::NONE`] for the last child.
    pub next_sibling: OptionNodeId,
}

/// The whole document AST.
///
/// Owns the source [`text`](Ast::text) once; nodes hold absolute [`Span`]s into it. There
/// is intentionally **no `Deserialize` derive**: consumers read the archived form
/// ([`ArchivedAst`]) in place. Deserializing back to a native `Ast` in the hot path is
/// forbidden by design (it would reintroduce a per-node allocation and defeat zero-copy).
#[derive(Archive, Serialize, Debug, Clone, PartialEq, Eq)]
pub struct Ast {
    /// All nodes; index with a [`NodeId`]. `nodes[root.0]` is the root.
    pub nodes: Vec<Node>,
    /// The full source text (BOM-stripped by the producer); spans index these bytes.
    pub text: String,
    /// The root node's id.
    pub root: NodeId,
}

// ── Zero-copy accessors over the archived form ───────────────────────────────────────
//
// Rules operate on `&ArchivedAst` / `&ArchivedNode`. These thin accessors decode the
// little-endian archived integers back into the ergonomic native id/kind/span types
// without copying the tree. A richer `NodeRef` facade is layered on top in the PDK.

impl ArchivedSpan {
    /// Decode to a native [`Span`].
    #[inline]
    #[must_use]
    pub const fn get(&self) -> Span {
        Span {
            start: self.start.to_native(),
            end: self.end.to_native(),
        }
    }
}

impl ArchivedNodeId {
    /// Decode to a native [`NodeId`].
    #[inline]
    #[must_use]
    pub const fn get(&self) -> NodeId {
        NodeId(self.0.to_native())
    }
}

impl ArchivedOptionNodeId {
    /// Decode to an [`Option<NodeId>`], honoring the `u32::MAX` sentinel.
    #[inline]
    #[must_use]
    pub const fn get(&self) -> Option<NodeId> {
        let raw = self.0.to_native();
        if raw == u32::MAX {
            None
        } else {
            Some(NodeId(raw))
        }
    }
}

impl ArchivedNodeKind {
    /// Decode to a native [`NodeKind`].
    #[inline]
    #[must_use]
    pub const fn get(&self) -> NodeKind {
        NodeKind(self.0.to_native())
    }
}

impl ArchivedNode {
    /// The node's [`NodeKind`].
    #[inline]
    #[must_use]
    pub const fn kind(&self) -> NodeKind {
        self.kind.get()
    }
    /// The node's absolute [`Span`].
    #[inline]
    #[must_use]
    pub const fn span(&self) -> Span {
        self.span.get()
    }
    /// The parent [`NodeId`].
    #[inline]
    #[must_use]
    pub const fn parent(&self) -> NodeId {
        self.parent.get()
    }
    /// The first child, if any.
    #[inline]
    #[must_use]
    pub const fn first_child(&self) -> Option<NodeId> {
        self.first_child.get()
    }
    /// The next sibling, if any.
    #[inline]
    #[must_use]
    pub const fn next_sibling(&self) -> Option<NodeId> {
        self.next_sibling.get()
    }
}

impl ArchivedAst {
    /// The root node's [`NodeId`].
    #[inline]
    #[must_use]
    pub const fn root(&self) -> NodeId {
        self.root.get()
    }

    /// The full source text.
    #[inline]
    #[must_use]
    pub fn text(&self) -> &str {
        self.text.as_ref()
    }

    /// The number of nodes.
    #[inline]
    #[must_use]
    pub fn len(&self) -> usize {
        self.nodes.len()
    }

    /// Whether there are no nodes.
    #[inline]
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }

    /// The node with the given id, or `None` if out of range.
    #[inline]
    #[must_use]
    pub fn node(&self, id: NodeId) -> Option<&ArchivedNode> {
        self.nodes.get(id.0 as usize)
    }

    /// The source text covered by `span`, or `None` if the span is out of range or does
    /// not fall on UTF-8 boundaries.
    #[inline]
    #[must_use]
    pub fn text_of(&self, span: Span) -> Option<&str> {
        self.text().get(span.start as usize..span.end as usize)
    }
}

// ── Archive bridge ───────────────────────────────────────────────────────────────────
// The one place that serializes/accesses the frozen archive, so the rkyv configuration
// (pinned little-endian, 32-bit pointers, bytecheck) stays centralized here.

/// Serialize an [`Ast`] into its frozen archive. The returned buffer is correctly aligned
/// for [`access`].
pub fn to_archive(ast: &Ast) -> Result<rkyv::util::AlignedVec, rkyv::rancor::Error> {
    rkyv::to_bytes::<rkyv::rancor::Error>(ast)
}

/// Access an archived [`Ast`] in place (zero-copy), validating the bytes (`bytecheck`) so a
/// malformed or misaligned buffer is a recoverable `Err`, never UB. Use this for any bytes
/// the current process did not just produce with [`to_archive`].
pub fn access(bytes: &[u8]) -> Result<&ArchivedAst, rkyv::rancor::Error> {
    rkyv::access::<ArchivedAst, rkyv::rancor::Error>(bytes)
}

// ── Frozen-layout guards ─────────────────────────────────────────────────────────────
// Compile-time assertions on the archived layout. These fail the build (not just a test)
// if a field type or order changes the size/alignment of the frozen records.
const _: () = {
    use core::mem::{align_of, size_of};
    assert!(size_of::<ArchivedSpan>() == 8);
    assert!(size_of::<ArchivedNodeId>() == 4);
    assert!(size_of::<ArchivedOptionNodeId>() == 4);
    assert!(size_of::<ArchivedNodeKind>() == 4);
    // kind(4) + span(8) + parent(4) + first_child(4) + next_sibling(4) = 24, no padding.
    assert!(size_of::<ArchivedNode>() == 24);
    assert!(align_of::<ArchivedNode>() == 4);
};

#[cfg(test)]
mod tests {
    use super::*;

    /// A canonical 3-node tree: Root → Paragraph → Text over the text `"Hi"`.
    fn canonical_ast() -> Ast {
        let nodes = vec![
            Node {
                kind: NodeKind::ROOT,
                span: Span::new(0, 2),
                parent: NodeId(0), // root's parent is the root itself
                first_child: OptionNodeId::some(NodeId(1)),
                next_sibling: OptionNodeId::NONE,
            },
            Node {
                kind: NodeKind::PARAGRAPH,
                span: Span::new(0, 2),
                parent: NodeId(0),
                first_child: OptionNodeId::some(NodeId(2)),
                next_sibling: OptionNodeId::NONE,
            },
            Node {
                kind: NodeKind::TEXT,
                span: Span::new(0, 2),
                parent: NodeId(1),
                first_child: OptionNodeId::NONE,
                next_sibling: OptionNodeId::NONE,
            },
        ];
        Ast {
            nodes,
            text: String::from("Hi"),
            root: NodeId(0),
        }
    }

    #[test]
    fn option_node_id_sentinel() {
        assert_eq!(OptionNodeId::NONE.get(), None);
        assert!(OptionNodeId::NONE.is_none());
        assert_eq!(OptionNodeId::some(NodeId(7)).get(), Some(NodeId(7)));
        assert_eq!(OptionNodeId::some(NodeId(0)).get(), Some(NodeId(0)));
        assert!(!OptionNodeId::some(NodeId(0)).is_none());
    }

    #[test]
    fn nodekind_open_enum_roundtrips_and_tolerates_unknown() {
        for k in [
            NodeKind::ROOT,
            NodeKind::PARAGRAPH,
            NodeKind::TEXT,
            NodeKind::FOOTNOTE_REFERENCE,
            NodeKind::MDXJS_ESM,
        ] {
            assert_eq!(NodeKind::from_u32(k.as_u32()), k);
            assert!(k.is_known());
        }
        assert_eq!(NodeKind::COUNT, 34);
        assert_eq!(NodeKind::MDXJS_ESM.as_u32(), 33); // last known
        assert!(!NodeKind::from_u32(34).is_known());

        // An unknown kind from a newer producer is preserved, not rejected.
        let unknown = NodeKind::from_u32(9_999);
        assert!(!unknown.is_known());
        assert_eq!(unknown.as_u32(), 9_999);
    }

    #[test]
    fn checked_access_roundtrip_and_traverse() {
        let ast = canonical_ast();
        let bytes = rkyv::to_bytes::<rkyv::rancor::Error>(&ast).unwrap();
        let archived = rkyv::access::<ArchivedAst, rkyv::rancor::Error>(&bytes).unwrap();

        assert_eq!(archived.root(), NodeId(0));
        assert_eq!(archived.len(), 3);
        assert_eq!(archived.text(), "Hi");

        let root = archived.node(NodeId(0)).unwrap();
        assert_eq!(root.kind(), NodeKind::ROOT);
        assert_eq!(root.parent(), NodeId(0));
        assert_eq!(root.first_child(), Some(NodeId(1)));
        assert_eq!(root.next_sibling(), None);

        let text_node = archived.node(NodeId(2)).unwrap();
        assert_eq!(text_node.kind(), NodeKind::TEXT);
        assert_eq!(text_node.first_child(), None);
        assert_eq!(archived.text_of(text_node.span()), Some("Hi"));

        assert!(archived.node(NodeId(3)).is_none());
    }

    #[test]
    fn spans_index_utf8_bytes() {
        // `Span` is an absolute *byte* range; multibyte CJK text slices correctly.
        let ast = Ast {
            nodes: vec![Node {
                kind: NodeKind::ROOT,
                span: Span::new(0, 9),
                parent: NodeId(0),
                first_child: OptionNodeId::NONE,
                next_sibling: OptionNodeId::NONE,
            }],
            text: String::from("見出し"), // 3 chars, 9 UTF-8 bytes
            root: NodeId(0),
        };
        let bytes = rkyv::to_bytes::<rkyv::rancor::Error>(&ast).unwrap();
        let archived = rkyv::access::<ArchivedAst, rkyv::rancor::Error>(&bytes).unwrap();
        assert_eq!(archived.text_of(Span::new(0, 9)), Some("見出し"));
        assert_eq!(archived.text_of(Span::new(0, 6)), Some("見出"));
        // A span that splits a multibyte char is rejected (no panic, no garbage).
        assert_eq!(archived.text_of(Span::new(0, 1)), None);
    }

    #[test]
    fn checked_access_rejects_garbage() {
        // Truncated / nonsense bytes must surface as a recoverable `Err`, never UB.
        let garbage = [0xFFu8; 9];
        let result = rkyv::access::<ArchivedAst, rkyv::rancor::Error>(&garbage);
        assert!(result.is_err());
    }

    #[test]
    fn golden_archived_layout_is_frozen() {
        let ast = canonical_ast();
        let bytes = rkyv::to_bytes::<rkyv::rancor::Error>(&ast).unwrap();

        // The frozen `AstCoreV1` wire image of `canonical_ast()`. Regenerate ONLY when the
        // ABI is deliberately changed (a major-version act): run this test, copy the
        // `actual` array printed on failure, and update both this constant and the
        // version. An accidental change (field reorder, endianness, rkyv upgrade) trips
        // this and must be investigated, not blindly re-baselined.
        //
        // Layout (little-endian, 24-byte nodes, `u32::MAX` = none, 32-bit rel pointers):
        #[rustfmt::skip]
        const EXPECTED: &[u8] = &[
            // node 0 — Root:      kind=0      span{0,2}      parent=0   child=1     sib=none
            0,0,0,0,   0,0,0,0, 2,0,0,0,   0,0,0,0,   1,0,0,0,    255,255,255,255,
            // node 1 — Paragraph: kind=1      span{0,2}      parent=0   child=2     sib=none
            1,0,0,0,   0,0,0,0, 2,0,0,0,   0,0,0,0,   2,0,0,0,    255,255,255,255,
            // node 2 — Text:      kind=17     span{0,2}      parent=1   child=none  sib=none
            17,0,0,0,  0,0,0,0, 2,0,0,0,   1,0,0,0,   255,255,255,255, 255,255,255,255,
            // Ast.nodes: ArchivedVec { rel_ptr = -72 (→ node 0), len = 3 }
            184,255,255,255, 3,0,0,0,
            // Ast.text: ArchivedString — "Hi" stored inline (rkyv small-string optimization)
            72,105, 255,255,255,255,255,255,
            // Ast.root: NodeId(0)
            0,0,0,0,
        ];

        assert_eq!(
            bytes.as_slice(),
            EXPECTED,
            "AstCoreV1 wire layout changed — actual ({} bytes) = {:?}",
            bytes.len(),
            bytes.as_slice(),
        );
    }

    #[test]
    fn archive_bridge_roundtrips() {
        let ast = canonical_ast();
        let bytes = to_archive(&ast).unwrap();
        let archived = access(&bytes).unwrap();
        assert_eq!(archived.root(), NodeId(0));
        assert_eq!(archived.len(), 3);
        assert_eq!(archived.text(), "Hi");
    }

    #[test]
    fn span_and_archive_size_helpers() {
        assert_eq!(Span::new(2, 7).len(), 5);
        assert_eq!(Span::new(7, 2).len(), 0); // inverted → saturating 0
        assert!(Span::new(3, 3).is_empty());
        assert!(!Span::new(3, 4).is_empty());

        let bytes = to_archive(&canonical_ast()).unwrap();
        let archived = access(&bytes).unwrap();
        assert!(!archived.is_empty());
    }
}
